version: '3.7'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  # Permite acceso sin contraseña
      MYSQL_DATABASE: db_conecta_campo
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  springboot:
    build: ./springboot
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_conecta_campo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:  # Dejar vacío para indicar que no hay contraseña

  react:
    build: ./react
    ports:
      - "80:80"
    depends_on:
      - springboot
